services:

  frontend:
    build:
      context: ./app/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  
  backend:
    build:
      context: ./app/backend
    ports:
      - "5000:5000"
    volumes:
      - ./app/backend:/app
      - /app/node_modules
    env_file:
      - ./app/backend/.env
    depends_on:
      - redis
      - postgres
  
  worker:
    build:
      context: ./app/worker
    volumes:
      - ./app/worker:/app
      - ./app/worker/temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      ./app/worker/.env
    depends_on:
      - redis
  
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Web-Compiler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: